# when site is built, @stackbit/stackbit-pull fetches the data from CMS and populates 'title', 'baseURL' and 'params' fields
# The rest of the configuration fields are left untouched. You can add additional Hugo configuration fields as described here: https://gohugo.io/getting-started/configuration/
# If you want to extend 'params' with additional fields, add them in CMS.title: Stackbit Fjord Theme
baseURL: /
taxonomies:
  stub: stub
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
